name: GitHub Metrics

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics.svg
          user: JellyWilliam
          committer_message: "Update assets/metrics.svg - [Skip GitHub Action]"

          template: classic
          base: ""
          base_skip: yes

          plugin_languages: true
          plugin_languages_sections: most-used
          plugin_languages_categories: programming
          plugin_languages_limit: 6
          plugin_languages_colors: github
          plugin_languages_details: percentage

          config_padding: 5%
          config_output: svg
          config_timezone: Europe/Moscow
